spring.application.name=Photo Marketplace Application

# Base configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/photo_marketplace_app
spring.datasource.username=
spring.datasource.password=
logging.level.org.hibernate.persister.entity=ERROR

spring.mvc.hiddenmethod.filter.enabled=true

app.photographer.password=
app.client.password=