spring.application.name=Photo Marketplace Quote Service
server.port=${QUOTE_SERVICE_PORT:8081}

spring.datasource.url=${QUOTE_DB_URL:jdbc:mysql://localhost:3306/photo_marketplace_quote_db?createDatabaseIfNotExist=true}
spring.datasource.username=${QUOTE_DB_USERNAME:}
spring.datasource.password=${QUOTE_DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info
